-- Schema from the supplied normalized 3x-ui export; no row data.
CREATE TABLE `inbounds` (`id` integer PRIMARY KEY AUTOINCREMENT,`user_id` integer,`up` integer,`down` integer,`total` integer,`remark` text,`sub_sort_index` integer DEFAULT 1,`enable` numeric,`expiry_time` integer,`traffic_reset` text DEFAULT "never",`last_traffic_reset_time` integer DEFAULT 0,`listen` text,`port` integer,`protocol` text,`settings` text,`stream_settings` text,`tag` text,`sniffing` text,`node_id` integer,`share_addr_strategy` text DEFAULT "node",`share_addr` text,`origin_node_guid` text, `traffic_reset_day` integer DEFAULT 1, `disable_flow` numeric DEFAULT false,CONSTRAINT `uni_inbounds_tag` UNIQUE (`tag`));

CREATE TABLE `clients` (`id` integer PRIMARY KEY AUTOINCREMENT,`email` text NOT NULL,`sub_id` text,`uuid` text,`password` text,`auth` text,`flow` text,`security` text,`reverse` text,`limit_ip` integer,`total_gb` integer,`expiry_time` integer,`enable` numeric DEFAULT true,`tg_id` integer,`group_name` text DEFAULT "",`comment` text,`reset` integer DEFAULT 0,`created_at` integer,`updated_at` integer, `wg_private_key` text, `wg_public_key` text, `wg_allowed_ips` text, `wg_pre_shared_key` text, `wg_keep_alive` integer DEFAULT 0, `secret` text, `ad_tag` text DEFAULT "", `wg_forwarded_ports` text, `limit_hwid` integer DEFAULT 0, `reset_day` integer DEFAULT 0, `reset_max` integer DEFAULT 0, `traffic_reset` text DEFAULT "never", `traffic_reset_day` integer DEFAULT 1, `sync_orphaned_at` integer DEFAULT 0);

CREATE TABLE `client_inbounds` (`client_id` integer,`inbound_id` integer,`flow_override` text,`created_at` integer,PRIMARY KEY (`client_id`,`inbound_id`));

CREATE TABLE "client_traffics"  (`id` integer PRIMARY KEY AUTOINCREMENT,`inbound_id` integer,`enable` numeric,`email` text,`up` integer,`down` integer,`expiry_time` integer,`total` integer,`reset` integer DEFAULT 0,`last_online` integer DEFAULT 0, `last_sub_fetch` integer DEFAULT 0, `reset_day` integer DEFAULT 0, `reset_max` integer DEFAULT 0, `reset_count` integer DEFAULT 0,CONSTRAINT `uni_client_traffics_email` UNIQUE (`email`),CONSTRAINT `fk_inbounds_client_stats` FOREIGN KEY (`inbound_id`) REFERENCES `inbounds`(`id`));

CREATE TABLE `api_tokens` (`id` integer PRIMARY KEY AUTOINCREMENT,`name` text NOT NULL,`token` text NOT NULL,`enabled` numeric DEFAULT true,`created_at` integer, `scope` text NOT NULL DEFAULT "admin", `expires_at` integer NOT NULL DEFAULT 0);

CREATE TABLE `hosts` (`id` integer PRIMARY KEY AUTOINCREMENT,`group_id` text,`inbound_id` integer NOT NULL,`sort_order` integer DEFAULT 0,`remark` text,`server_description` text,`is_disabled` numeric DEFAULT false,`is_hidden` numeric DEFAULT false,`tags` text,`address` text,`port` integer DEFAULT 0,`security` text DEFAULT "same",`sni` text,`host_header` text,`path` text,`alpn` text,`fingerprint` text,`override_sni_from_address` numeric,`keep_sni_blank` numeric,`pinned_peer_cert_sha256` text,`verify_peer_cert_by_name` text,`allow_insecure` numeric,`ech_config_list` text,`mux_params` text,`sockopt_params` text,`final_mask` text,`vless_route` text,`exclude_from_sub_types` text,`mihomo_ip_version` text,`mihomo_x25519` numeric,`shuffle_host` numeric,`node_guids` text,`created_at` integer,`updated_at` integer);

CREATE TABLE `settings` (`id` integer PRIMARY KEY AUTOINCREMENT,`key` text,`value` text);

CREATE TABLE `users` (`id` integer PRIMARY KEY AUTOINCREMENT,`username` text,`password` text,`login_epoch` integer DEFAULT 0);
