#!/usr/bin/env python3
"""Keep the cloud-config payload identical to the standalone startup script."""
from __future__ import annotations

import argparse
from pathlib import Path
import sys


PROJECT = Path(__file__).resolve().parents[1]
DESTINATION = PROJECT / "cloud-init/xupdate.yaml"


def render() -> str:
    script = (PROJECT / "scripts/bootstrap.sh").read_text()
    content = """#cloud-config
# Generated by scripts/render-cloud-init.py; edit scripts/bootstrap.sh instead.
# Ubuntu 24.04+ / Debian 12+, amd64 or arm64, with systemd and cloud-init.
# Defaults to the main branch. For a fixed revision, replace main in runcmd.
# Provider networking, resolver settings, SSH users, and keys remain in effect.
write_files:
  - path: /var/lib/xupdate-bootstrap/bootstrap.sh
    owner: root:root
    permissions: '0700'
    content: |
"""
    content += "".join("      " + line + "\n" for line in script.splitlines())
    content += """runcmd:
  - [bash, /var/lib/xupdate-bootstrap/bootstrap.sh, --ref, main]
"""
    if len(content.encode("utf-8")) > 16 * 1024:
        raise ValueError("Cloud-config exceeds the EC2 16 KiB user-data limit")
    return content


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if the committed YAML is stale")
    args = parser.parse_args()
    content = render()
    if args.check:
        if not DESTINATION.is_file() or DESTINATION.read_text() != content:
            print("Run python3 scripts/render-cloud-init.py to refresh cloud-init/xupdate.yaml", file=sys.stderr)
            return 1
        print(f"Cloud-config matches bootstrap.sh ({len(content.encode('utf-8'))} bytes).")
    else:
        DESTINATION.parent.mkdir(parents=True, exist_ok=True)
        DESTINATION.write_text(content)
        print("Updated cloud-init/xupdate.yaml")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
